import React from 'react';
import { PlannerTripPlan } from '@/constants/aiPlanner';

interface BudgetBreakdownProps {
  plan: PlannerTripPlan;
}

export function BudgetBreakdown({ plan }: BudgetBreakdownProps) {
  return (
    <div className="flex flex-col gap-5 text-left w-full">
      <h2 className="text-xl md:text-2xl font-bold text-foreground">Estimated Budget Breakdown</h2>
      
      <div className="p-6 rounded-2xl border border-border/80 bg-surface/30 flex flex-col gap-5">
        <div className="flex justify-between items-center pb-3 border-b border-border/50">
          <div>
            <h4 className="font-semibold text-sm text-foreground">Cost Distribution</h4>
            <span className="text-[10px] text-muted">Estimated price allocations per traveler</span>
          </div>
          <span className="text-lg font-extrabold text-primary">${plan.estimatedTotal} Total</span>
        </div>

        <div className="flex flex-col gap-4">
          {plan.budgetBreakdown.map((item, idx) => (
            <div key={idx} className="flex flex-col gap-1.5">
              <div className="flex justify-between text-xs font-semibold text-foreground/90">
                <span>{item.category}</span>
                <span className="text-muted">
                  ${item.estimatedCost} ({item.percentage}%)
                </span>
              </div>
              
              {/* Custom CSS Progress Bar */}
              <div className="w-full bg-background rounded-full h-2 overflow-hidden border border-border/40">
                <div
                  className="bg-primary h-full rounded-full transition-all duration-500 ease-out"
                  style={{ width: `${item.percentage}%` }}
                />
              </div>
            </div>
          ))}
        </div>
        
        <p className="text-[10px] text-muted italic mt-2 text-center">
          * Costs are generated by AI based on real-time market averages and budget preferences. Actual prices may vary depending on seasons.
        </p>
      </div>
    </div>
  );
}
